apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole                                          # permission for all namespaces within a cluster
metadata:
  name: multi-namespace-role                                # this means that this role is 
                                                            # for all namespaces within a cluster
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]